#%RAML 1.0
title: Testing form-data API!

/form-data:
  /{form-id}/file:
    post:
      body:
        multipart/form-data:
          properties:
            filename:
              description: uploaded attachment file
              required: true
              type: file
      responses:
        200:
          body:
            application/json: