enableAllureTestReportStage: false
mavenSettingsXmlId: ab7820eb-e393-4e88-9962-92104044ed75
projectType: extension
additionalTestConfigs:
  jdk17-4.9.x:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DruntimeVersion=4.9.6 -DruntimeProduct=MULE_EE
  jdk17-4.8.x:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DruntimeVersion=4.8.6 -DruntimeProduct=MULE_EE
  jdk17-4.7.x:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DruntimeVersion=4.7.4 -DruntimeProduct=MULE_EE
  jdk17-4.6.x:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DruntimeVersion=4.6.19 -DruntimeProduct=MULE_EE
