#%RAML 1.0
---
title: Some API for testing the console :D!

/important:
  get:
  /resource:
    get:
      responses:
        200:
          body:
            application/json:
                example: !include example.json
