#%RAML 1.0
---
title: API for test errors!

/raiseError:
  get:
    responses:
      200:
        body:
            application/json:
/onErrorContinue:
  get:
    responses:
      200:
        body:
            application/json:
/onErrorPropagate:
  get:
    responses:
      200:
        body:
            application/json:
/errorWithMuleMessageIsBeingPropagated:
  get:
    responses:
      200:
        body:
           application/json:
