#%RAML 1.0
title: Testing API for query-params
version: v1

/any-value:
  description: Simple endpoint with a query parameter of type any
  get:
    queryParameters:
        anytype:
          description: Paramter of type any
          type: any
          example: "Any value"