#%RAML 1.0
title: Headers Test Case

/datetime2616:
  get:
    headers:
      X-ModifiedSince:
        type: datetime
        format: rfc2616
  post:
    headers:
      X-MaxRows:
        type: integer
        required: false
      defaultHeaderValue:
        type: string
        default: "hola-header"
        required: false

/test-array-object-header:
  get:
    headers:
      array-header:
        required: false
        type: array
        items:
          type: object
          properties:
            type: string
            value: string

/test-array-string-header:
  get:
    headers:
      array-header:
        required: false
        type: array
        items:
          type: string

/test-array-number-header:
  get:
    headers:
      array-header:
        required: false
        type: array
        items:
          type: number

/test-array-enum-header:
  get:
    headers:
      array-header:
        required: false
        type: array
        items:
          type: string
          enum: ["SFO", "LAX", "CLE", "DAL", "NUY", "PHL", "NJC"]

/test-array-datetime-header:
  get:
    headers:
      array-header:
        required: false
        type: array
        items:
          type: datetime

/test-array-datetime2616-header:
  get:
    headers:
      array-header:
        required: false
        type: array
        items:
          type: datetime
          format: rfc2616

/multiplicity:
  get:
    responses:
      200:
        body:
          application/json:
  post:
    body:
      application/json: