#%RAML 1.0
---
title: URI Params Combinations
version: 1.0
baseUri: https://{apiDomain}.ec2.amazonaws.com
baseUriParameters:
  apiDomain:
    enum: [ "domain" ]

/noUriParamsOverridden:
  get:
    description:
    responses:
      200:
        body:
          application/json:
  put:
    description:
    body:
      application/json:
    responses:
      204:
      404:

/noUriParamsButRequired/{testParam}:
  get:
    description:
    responses:
      200:
        body:
          application/json:
  put:
    description:
    body:
      application/json:
    responses:
      204:
      404:

/templateUriParamsInResource/{testParam}:
  uriParameters:
    testParam:
      enum: [ "resource" ]
  get:
    description:
    responses:
      200:
        body:
          application/json:
  put:
    description:
    body:
      application/json:
    responses:
      204:
      404:

/baseUriParamsOverriddenInResource/{testParam}:
  uriParameters:
    testParam:
      enum: [ "resource" ]
    apiDomain:
      enum: [ "resource-domain" ]
  get:
    description:
    responses:
      200:
        body:
          application/json:
  put:
    description:
    body:
      application/json:
    responses:
      204:
      404: