#%RAML 1.0
title: Test consistency between query parameters and query string validation
version: v1

types:
  stringItem:
    type: string
    minLength: 2
    maxLength: 5
    default: "def"
  numericItem:
    type: number
    default: 123.456
  integerItem:
    type: integer
    default: 789
  booleanItem:
    type: boolean
    default: false
  datetimeItem:
    type: datetime
    default: "2016-02-28T16:41:41.090Z"
  unionItem:
    type: string | any
    default: "something"
  nonStringUnionItem:
    type: number | boolean
    default: 123
  objectItem:
    type: object
    additionalProperties: false
    properties:
      stringProp?: string
      numberProp?: number
      integerProp?: integer
      booleanProp?: boolean
      datetimeProp?: datetime
      unionProp?: string | any
      nonStringUnionItem?: number | boolean
      stringProps?: string[]
      numberProps?: number[]
      integerProps?: integer[]
      booleanProps?: boolean[]
      datetimeProps?: datetime[]
  stringItems:
    type: array
    items: stringItem
    default: ["def","ault"]
  numericItems:
    type: array
    items: numericItem
    default: [123.456,789.123]
  integerItems:
    type: array
    items: integerItem
    default: [123,456]
  booleanItems:
    type: array
    items: booleanItem
    default: [True,false]
  datetimeItems:
    type: array
    items: datetimeItem
    default: ["2016-02-28T16:41:41.090Z","2018-12-18T16:41:41.090Z"]
  unionItems:
    type: array
    items: unionItem
    default: ["some","default","value"]
  nonStringUnionItems:
    type: array
    items: nonStringUnionItem
    default: [123,true,4.23]
  objectItems:
    type: array
    items: objectItem
  query:
    type: object
    additionalProperties: false
    properties:
      stringItemParam?:
        type: stringItem
      numericItemParam?:
        type: numericItem
      integerItemParam?:
        type: integerItem
      booleanItemParam?:
        type: booleanItem
      datetimeItemParam?:
        type: datetimeItem
      unionItemParam?:
        type: unionItem
      nonStringUnionItemParam?:
        type: nonStringUnionItem
      objectItemParam?:
        type: objectItem
      stringItemParams?:
        type: stringItems
      numericItemParams?:
        type: numericItems
      integerItemParams?:
        type: integerItems
      booleanItemParams?:
        type: booleanItems
      datetimeItemParams?:
        type: datetimeItems
      unionItemParams?:
        type: unionItems
      nonStringUnionItemParams?:
        type: nonStringUnionItems
      objectItemParams?:
        type: objectItems

/testQueryParams:
  get:
    queryParameters:
      stringItemParam?:
        type: stringItem
      numericItemParam?:
        type: numericItem
      integerItemParam?:
        type: integerItem
      booleanItemParam?:
        type: booleanItem
      datetimeItemParam?:
        type: datetimeItem
      unionItemParam?:
        type: unionItem
      nonStringUnionItemParam?:
        type: nonStringUnionItem
      objectItemParam?:
        type: objectItem
      stringItemParams?:
        type: stringItems
      numericItemParams?:
        type: numericItems
      integerItemParams?:
        type: integerItems
      booleanItemParams?:
        type: booleanItems
      datetimeItemParams?:
        type: datetimeItems
      unionItemParams?:
        type: unionItems
      nonStringUnionItemParams?:
        type: nonStringUnionItems
      objectItemParams?:
        type: objectItems
    responses:
      200:
/testQueryString:
  get:
    queryString:
      type: query
    responses:
      200: