#%RAML 1.0
title: Sample API
version: v1

/resource/{version}:
  get:
    description: |
      Retrieve resource(s)
    responses:
      200:
        description: |
          Successfully retrieved resource(s)
/constrains:
  /{id}:
    uriParameters:
      id:
        type: integer
        minimum: 1
        maximum: 5
    get:

    /{id2}:
      uriParameters:
        id2:
          enum: [one, two, three]
      get:
