#%RAML 1.0
title: Illustrate query parameter variations
types:
  lat-long: # lat & long required; mutually exclusive with location
    properties:
      lat: number
      long: number
  loc: # location required; mutually exclusive with lat & long
    properties:
      location:
  paging: # each is optional, not exclusive with anything
    properties:
      start?: number
      page-size?: number
  Email:
    type: object
    properties:
      subject: string
      to: array
      body: string
  Emails:
    type: Email[]
    minItems: 1
    uniqueItems: true
    example: # example that contains array
      - # start item 1
        subject: My Email 1
        to: [ John, Ana ]
        body: This is the text for email 1.
      - # start item 2
        subject: My Email 2
        to: [ Mike ]
        body: This is the text for email 2.

/locations:
  get:
    queryString:
      type: [paging,  lat-long | loc ]
      examples:
        first:
          value:
            start: 2
            lat: 12
            long: 13
        second:
          value:
            start: 2
            page-size: 20
            location: 1,2

/emails:
  get:
    queryString:
      type: Emails
      default: []

  /details:
    get:
      queryString:
        type: Email

  /historySince:
    get:
      queryString:
        type: datetime
